apiVersion: v1
kind: Service
metadata:
  name: ml-service
  namespace: ml-deployment
  labels:
    app.kubernetes.io/name: ml-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: ml-service
---
apiVersion: v1
kind: Service
metadata:
  name: ml-service-headless
  namespace: ml-deployment
  labels:
    app.kubernetes.io/name: ml-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 8000
      targetPort: http
  selector:
    app.kubernetes.io/name: ml-service
