from pptx import Presentation
from pptx.util import Inches, Pt
import os

class PPTAgent:
    """
    Agent for generating PowerPoint presentations.
    用于生成 PowerPoint 演示文稿的代理。
    用於生成 PowerPoint 簡報的代理。
    """

    def __init__(self, output_file: str = "output.pptx"):
        self.output_file = output_file
        self.prs = Presentation()

    def create_title_slide(self, title: str, subtitle: str):
        """
        Create a title slide.
        创建标题幻灯片。
        創建標題投影片。
        """
        slide_layout = self.prs.slide_layouts[0] # Title Slide
        slide = self.prs.slides.add_slide(slide_layout)

        title_placeholder = slide.shapes.title
        subtitle_placeholder = slide.placeholders[1]

        title_placeholder.text = title
        subtitle_placeholder.text = subtitle

    def add_summary_slide(self, heading: str, bullet_points: list[str]):
        """
        Add a content slide with bullet points.
        添加带有要点的内容幻灯片。
        添加帶有要點的內容投影片。
        """
        slide_layout = self.prs.slide_layouts[1] # Title and Content
        slide = self.prs.slides.add_slide(slide_layout)

        # Set Heading / 设置标题 / 設置標題
        title_shape = slide.shapes.title
        title_shape.text = heading

        # Set Body / 设置正文 / 設置正文
        body_shape = slide.placeholders[1]
        tf = body_shape.text_frame

        for point in bullet_points:
            p = tf.add_paragraph()
            p.text = point
            p.level = 0

    def save(self):
        """Save the presentation / 保存演示文稿 / 保存簡報"""
        self.prs.save(self.output_file)
        print(f"Presentation saved to {self.output_file}")

if __name__ == "__main__":
    agent = PPTAgent("saca_report.pptx")
    agent.create_title_slide("SACA Daily Report", "Generated by AI Agent")
    agent.add_summary_slide("Key Updates / 关键更新 / 關鍵更新", [
        "Memory initialized in Excel.",
        "LLM Bridge connected.",
        "Blueprint created."
    ])
    agent.save()
